#!/usr/bin/env python3
# pre-trigger build (v0.7.0); reassess when trigger fires per
# governance/SKILL-DISCOVERABILITY.md (50+ skills).
"""
gen-index.py — generate INDEX.md at the library root listing every skill.

Per governance/SKILL-DISCOVERABILITY.md (which v0.7.0 flips Deferred → Built
ahead of trigger). The INDEX.md is a living artifact regenerated on every
release; --check mode reports stale status without writing.

INDEX.md columns:
- name (with link to SKILL.md path)
- archetype
- version
- tags
- one-line description (truncated to ~120 chars)

Exit codes:
  0  generated successfully (or --check passed)
  1  --check found stale INDEX.md
  2  invocation problem (no skills, malformed YAML)

Usage:
  gen-index.py                # writes INDEX.md
  gen-index.py --check        # exit 1 if INDEX.md needs regeneration
  gen-index.py --output /tmp/INDEX.md

Dependencies: PyYAML (via _skill_io) + stdlib.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from _skill_io import iter_live_skills, parse_skill


HEADER = """# Library Index

Generated by `scripts/gen-index.py`. Living artifact regenerated on every
release. Do not edit by hand — re-run `make index` after authoring or
modifying skills.

Per `governance/EXTENSION-POINTS.md` §5, INDEX.md is a stable contract:
columns and format may evolve in MINOR bumps, but the artifact's existence
and authoring (script-generated, never hand-edited) is invariant.

Total skills: {count}

| Skill | Archetype | Version | Tags | Description |
|---|---|---|---|---|
"""


def render_index(plugin_root: Path) -> str:
    rows: list[str] = []
    skills_seen = []
    for skill_md in iter_live_skills(plugin_root):
        try:
            doc = parse_skill(skill_md)
        except ValueError:
            continue
        name = str(doc.frontmatter.get("name") or skill_md.parent.name)
        meta = doc.frontmatter.get("metadata") or {}
        version = str(meta.get("version") or "?")
        archetype = str(meta.get("archetype") or "?")
        tags = meta.get("tags") or []
        if not isinstance(tags, list):
            tags = []
        tag_str = ", ".join(str(t) for t in tags if isinstance(t, str)) or "—"
        desc = str(doc.frontmatter.get("description") or "").strip()
        # One-line: collapse whitespace, escape pipes, truncate to ~120 chars.
        one = " ".join(desc.split()).replace("|", "\\|")[:120]
        rel_path = skill_md.relative_to(plugin_root)
        rows.append(
            f"| [`{name}`]({rel_path}) | {archetype} | {version} | {tag_str} | {one} |"
        )
        skills_seen.append(name)
    rows.sort(key=lambda r: r.split("`")[1])  # sort by skill name
    out = HEADER.format(count=len(rows)) + "\n".join(rows) + "\n"
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--output", type=Path, default=None,
                        help="output path (default: <root>/INDEX.md)")
    parser.add_argument("--check", action="store_true",
                        help="report whether INDEX.md is stale; exit 1 if so")
    args = parser.parse_args(argv)

    if not (args.root / "skills").is_dir():
        sys.stderr.write(f"error: no skills/ directory under {args.root}\n")
        return 2

    output_path: Path = args.output or (args.root / "INDEX.md")
    rendered = render_index(args.root)

    if args.check:
        if not output_path.is_file():
            sys.stderr.write(f"INDEX.md does not exist at {output_path}; run gen-index.py.\n")
            return 1
        existing = output_path.read_text(encoding="utf-8")
        if existing == rendered:
            print(f"INDEX.md is fresh ({output_path}).")
            return 0
        sys.stderr.write(f"INDEX.md is stale at {output_path}. Re-run gen-index.py.\n")
        return 1

    output_path.write_text(rendered, encoding="utf-8")
    print(f"Wrote {output_path} ({rendered.count(chr(10))} lines).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
